package ru.mirea.task3.exs1;


import java.util.Random;

public class RandomArray {

    private static void print(int[] array) {
        if (array == null) return;
        for (int number : array) {
            System.out.printf("%d ", number);
        }
    }

    private static void fillMathRandom(int[] array) {
        if (array == null) return;
        for (int i = 0; i < array.length; i++) {
            array[i] = (int)(Math.random() * 1000);
        }
    }

    private static void fillRandom(int[] array) {
        if (array == null) return;
        Random rand = new Random();
        for (int i = 0; i < array.length; i++) {
            array[i] = rand.nextInt(1001);
        }
    }

    public static void sort(int[] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = i + 1; j < array.length; j++) {
                if (array[i] > array[j]) {
                    int tmp = array[i];
                    array[i] = array[j];
                    array[j] = tmp;
                }
            }
        }
    }

    public static void main(String[] args) {
        int[] numberArray = new int[(int)(Math.random() * 20)];

        fillMathRandom(numberArray);
        System.out.println("Array generated by Math.random:");
        print(numberArray);

        sort(numberArray);
        System.out.println("\nFirst sorted array:");
        print(numberArray);

        fillRandom(numberArray);
        System.out.println("\nArray generated by Random:");
        print(numberArray);

        sort(numberArray);
        System.out.println("\nSecond sorted array:");
        print(numberArray);
    }
}